server:
  port: ${port:9001}
spring:
  application:
    name: service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.58.167:3306/building?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: root
mybatis:
  type-aliases-package: com.zybe.pojo
  mapper-locations:
    - classpath:/*.xml
mapper:
  wrap-keyword: "`{0}`"
properties:
  auth: gateway