server:
  port: ${port:10001}
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service
          uri: lb://service
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=auth, gateway
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "api.maven.host"
            allowedMethods:
              - GET
              - POST
      default-filters:
        - name: CircuitBreaker
          args:
            name: fallback
            fallbackUri: forward:/fallback